### ISSUE TITLE
Incorporate ArgoCD into k8s deployment script

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/gitops#2]
Incorporate ArgoCD into k8s deployment script to use with our helmfile script

**Comment by scanalesespinoza** [comment]
Basic installation is just and apply of this CRD -> https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml
That can be enought to start

**Comment by scanalesespinoza** [comment]
@bradmccoydev I installed ArgoDC with this steps, let me now if it resolve the issue:
`
 git clone https://github.com/argoproj/argo-cd.git
 cd argo-cd/
 kubectl create namespace argocd
 kubectl apply -n argocd --force -f manifests/install.yaml
 `
![image](https://user-images.githubusercontent.com/11546953/122656366-dc024c80-d127-11eb-9a02-0f0de0915f2d.png)

**Comment by bradmccoydev** [comment]
@scanalesespinoza nice one i will close the issue
