### ISSUE TITLE
Create Helm Chart for test app

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/gitops#8]

**Comment by scanalesespinoza** [comment]
Hi @bradmccoydev let me know if this repo can solve this issue, is a helm char to deploy ortelius monolith -> https://github.com/scanalesespinoza/ortelius-quickstart/tree/master/ortelius-k8s-chart

**Comment by bradmccoydev** [comment]
@scanalesespinoza looks awesome, yes that will solve this issue @Checksumz @tbulubas

**Comment by scanalesespinoza** [comment]
Hi, I already deploy the example aplication using this repo -> https://github.com/scanalesespinoza/ortelius-quickstart.git, only need to run './run-ortelius-into-minikube.sh', I'm Closing the issue as you mention
